### PR TITLE
Add DELETE function

### PR DESCRIPTION
**Pull request by luoyantao99**
- Add function for delete
- Test coverage 100%

### CODE REVIEW

**Review by haofrank — CHANGES_REQUESTED** [review]
we need the api info to README

**Comment by luoyantao99** [comment]
I think it's already added

**Review by haofrank — APPROVED** [review]

**Comment by haofrank** [comment]
> I think it's already added

Oh, yes I missed it🥹

**Review by ZzSteven-Wang — APPROVED** [review]
Looks good to me

**Pull request merged**
