### PR TITLE
Add category selection for the UI

### PR DESCRIPTION
**Pull request by luoyantao99**

### CODE REVIEW

**Comment by luoyantao99** [comment]
Dropdown menu added, need to add TDD and BDD test cases

**Comment by haofrank** [comment]
> Dropdown menu added, need to add TDD and BDD test cases

https://github.com/CSCI-GA-2820-FA23-001/products/blob/18169a53fd1024fa4664f653e7d7cdd82105028f/features/products.feature#L23

This line should change to that:
```
    And I select "SPORTS" in the "Category" dropdown
```

**Review by haofrank — CHANGES_REQUESTED** [review]
https://github.com/CSCI-GA-2820-FA23-001/products/blob/18169a53fd1024fa4664f653e7d7cdd82105028f/features/products.feature#L23

This line should change to that:
```
    And I select "SPORTS" in the "Category" dropdown
```

**Comment by luoyantao99** [comment]
Test case added, .feature file updated

**Review by haofrank — APPROVED** [review]

**Pull request merged**
